# Use the Bitnami Spark base image
FROM bitnami/spark:3.5.3

# Set working directory
# WORKDIR /opt/spark/app

USER root

# Set environment variables
ENV HOME=/opt/spark/home
ENV IVY_HOME=$HOME/.ivy2

# Create the Ivy cache directory so spark-submit can use it
RUN mkdir -p /opt/spark/home/.ivy2/local

# Copy the JAR into the image
COPY ./practica_creativa/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1-k8s.jar /home/ibdn/docker-k8s/practica_creativa/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar

# Copy models into the image (optional)
COPY ./practica_creativa/models/ /home/ibdn/docker-k8s/practica_creativa/models/
COPY ./practica_creativa/models/arrival_bucketizer_2.0.bin/metadata/ /home/ibdn/docker-k8s/practica_creativa/models/arrival_bucketizer_2.0.bin/metadata/


# No CMD needed, overridden by k8s Deployment
# RUN useradd -u 1000 sparkuser
