apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode1-pvc
  namespace: practica-creativa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datanode1-pvc
  namespace: practica-creativa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi