apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-namenode
  namespace: practica-creativa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-datanode
  namespace: practica-creativa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard