apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  namespace: practica-creativa
spec:
  type: NodePort
  selector:
    app: nifi
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30443
    - name: comm
      port: 5050
      targetPort: 5050
      nodePort: 30550