apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: practica-creativa
spec:
  type: NodePort                # Add this line to expose the service externally
  selector:
    app: spark-master
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8086
      targetPort: 8080
      name: ui
      nodePort: 30080          # Optional: specify nodePort in range 30000-32767
