apiVersion: v1
kind: Service
metadata:
    name: servicio-p5-7-prom
    namespace: practica-creativa
spec:
    type: NodePort
    ports:
        - port: 20000
          targetPort: 9090
          nodePort: 30017
    selector:
        role: comp-nub-p5-7-prom
